services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network
    environment:
      - CONFIG_PATH=/config.yaml

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "todo_user", "-d", "todo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres-data: